### PR TITLE
Fixes

### LINKED ISSUE #22: Quotes JSON naming convention
It is a good idea to follow **camelCase** for JSON objects. But the Quotes JSON file does it other way.

I planned to implement this as well in my PR, but then the open PR could not be merged. Also I wanted to know you thoughts on this before that.

### PR DESCRIPTION
**Pull request by TheLearneer**
Fix #22 

Also fix major JSON structure issues formed due to merging faulty PR's

### CODE REVIEW

**Comment by TheLearneer** [comment]
Holding it to be merged can cause further conflicts and issues, so I suggest to merge it as soon as possible for better maintainability of the repository.

**Comment by tachodril** [comment]
@TheLearneer  all the bugs due to json syntax has just been resolved.

**Comment by TheLearneer** [comment]
This PR also did what was discussed in #22 .. Anyways upto you

**Comment by tachodril** [comment]
> Holding it to be merged can cause further conflicts and issues, so I suggest to merge it as soon as possible for better maintainability of the repository.

Thanks @TheLearneer for the advice, I am trying to merge them as soon as possible.

**Comment by tachodril** [comment]
> This PR also did what was discussed in #22 .. Anyways upto you

@TheLearneer  Is it possible for you to do the changes in naming convention for quotes.json file again, as if i accept this commit, it would render a lot of complex merge conflicts.

**Comment by TheLearneer** [comment]
Sure I will... but what about #23 .. If you merge that now it will be one time job

**Pull request closed without merging**
